url: https://etoews.github.io
author: Everett Toews
description: Helping you shave narwhals
title: etoews
permalink: /blog/:year/:month/:day/:title/
paginate: 6
paginate_path: "page:num"
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
